schema_version = "1.0.0"
id = "Utilities_Gadget"
name = "Utilities Gadget"
version = "1.1.4"
tagline = "Batch rendering and model conversio"
maintainer = "hurcaguari"
type = "add-on"
tags = ["Mesh"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/hurcaguari/Blender-Utilities-Gadget"
copyright = []
